apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Testing
  description: Backstage Catalog
  annotations:
    # gitpod.io/host: gitpod.io
    github.com/project-slug: Musquan/backstage-catalog
    jira/project-key: 'SCRUM'
    jira/label: backstage-component:Testing
spec:
  type: application
  owner: ICS
  lifecycle: experimental
